In [4]:
import torch
batch = 2
seq_len = 6
d_model = 3
x = torch.arange(36, dtype=torch.float32).reshape(batch, seq_len, d_model)
x, x.mean(dim=1)

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.],
          [12., 13., 14.],
          [15., 16., 17.]],
 
         [[18., 19., 20.],
          [21., 22., 23.],
          [24., 25., 26.],
          [27., 28., 29.],
          [30., 31., 32.],
          [33., 34., 35.]]]),
 tensor([[ 7.5000,  8.5000,  9.5000],
         [25.5000, 26.5000, 27.5000]]))

In [4]:
d_block = 3
x = x.view(-1, d_block, d_model)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])

In [6]:
x = x.view(batch, -1, d_model)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])