In [25]:
d_chunk = 2
d_model = 8
for i in range(0, d_model, d_chunk):
    z[i:i+d_chunk:, i:i+d_chunk:] = torch.matmul(y[i:i+d_chunk:, i:i+d_chunk:], y[i:i+d_chunk:, i:i+d_chunk:])
y, z

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31],
         [32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47],
         [48, 49, 50, 51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60, 61, 62, 63]]),
 tensor([[   8,    9,    0,    0,    0,    0,    0,    0],
         [  72,   89,    0,    0,    0,    0,    0,    0],
         [   0,    0,  818,  855,    0,    0,    0,    0],
         [   0,    0, 1170, 1223,    0,    0,    0,    0],
         [   0,    0,    0,    0, 2924, 2997,    0,    0],
         [   0,    0,    0,    0, 3564, 3653,    0,    0],
         [   0,    0,    0,    0,    0,    0, 6326, 6435],
         [   0,    0,    0,    0,    0,    0, 7254, 7379]]))

In [10]:
import torch
seq_len = 6
d_k = 2
# seq_len, d_k: 6*2
a = torch.arange(12, dtype=torch.float).reshape(seq_len, d_k)
b = torch.arange(12, dtype=torch.float).reshape(seq_len, d_k)
a, b

(tensor([[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]),
 tensor([[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]))

In [11]:
d_chunk = 3
# nchunk, d_chunk, d_k: 2*3*2
a = a.view(-1, d_chunk, d_k)
b = b.view(-1, d_chunk, d_k)
a, b

(tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.]],
 
         [[ 6.,  7.],
          [ 8.,  9.],
          [10., 11.]]]),
 tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.]],
 
         [[ 6.,  7.],
          [ 8.,  9.],
          [10., 11.]]]))

In [12]:
# 2*3*2 @ 2*2*3 = 2*(3*3)
b = b.transpose(-1, -2)
dot = torch.matmul(a, b)
a, b, dot

(tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.]],
 
         [[ 6.,  7.],
          [ 8.,  9.],
          [10., 11.]]]),
 tensor([[[ 0.,  2.,  4.],
          [ 1.,  3.,  5.]],
 
         [[ 6.,  8., 10.],
          [ 7.,  9., 11.]]]),
 tensor([[[  1.,   3.,   5.],
          [  3.,  13.,  23.],
          [  5.,  23.,  41.]],
 
         [[ 85., 111., 137.],
          [111., 145., 179.],
          [137., 179., 221.]]]))

In [13]:
attn = torch.softmax(dot, dim=-1)
attn

tensor([[[1.5876e-02, 1.1731e-01, 8.6681e-01],
         [2.0611e-09, 4.5398e-05, 9.9995e-01],
         [2.3195e-16, 1.5230e-08, 1.0000e+00]],

        [[2.6103e-23, 5.1091e-12, 1.0000e+00],
         [2.9375e-30, 1.7139e-15, 1.0000e+00],
         [3.3057e-37, 5.7495e-19, 1.0000e+00]]])

In [11]:
import torch
max_len = 3
stride = 1
mask = torch.zeros(max_len, max_len, dtype=torch.bool)
for i in range(max_len):
    start = max(0, i - stride)
    end = min(max_len, i + stride + 1)
    mask[i, start:end] = True
mask

x = torch.arange(36).reshape(2, 2, 3, 3)
x.masked_fill_(mask, 99)
mask, x

(tensor([[ True,  True, False],
         [ True,  True,  True],
         [False,  True,  True]]),
 tensor([[[[99, 99,  2],
           [99, 99, 99],
           [ 6, 99, 99]],
 
          [[99, 99, 11],
           [99, 99, 99],
           [15, 99, 99]]],
 
 
         [[[99, 99, 20],
           [99, 99, 99],
           [24, 99, 99]],
 
          [[99, 99, 29],
           [99, 99, 99],
           [33, 99, 99]]]]))

In [22]:
import torch
idx = torch.tensor([0, 1, 0 ,1])
y = torch.arange(0, 36).reshape(4, 3, 3)
y, y[idx]
a = torch.tensor([0., 1., 0. ,1., 0, 0, 1, 1])
torch.where(a == 1)[0].dtype

torch.int64

In [5]:
import torch
seq_len = 5
causal_mask = torch.triu(torch.ones(seq_len, seq_len, dtype=torch.bool), diagonal=1)
~causal_mask

tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])

In [2]:
import torch
max_len = 8
d_model = 8
d_chunk = 2
mask = torch.zeros(max_len, max_len, dtype=torch.bool)
for i in range(0, d_model, d_chunk):
    mask[i:i+d_chunk, i:i+d_chunk] = True
mask

tensor([[ True,  True, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False, False],
        [False, False,  True,  True, False, False, False, False],
        [False, False,  True,  True, False, False, False, False],
        [False, False, False, False,  True,  True, False, False],
        [False, False, False, False,  True,  True, False, False],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True]])